backend = "etcd"
#client_cert = "/etc/confd/ssl/client.crt"
#client_key = "/etc/confd/ssl/client.key"
confdir = "/etc/confd"
debug = true
interval = 10
nodes = [
  "http://localhost:4001",
]
noop = false
prefix = "/"
quiet = false
#scheme = "https"
#srv_domain = "etcd.example.com"
verbose = true
watch = true
