[template]
keys = [
  "pebblescape/apps",
]
owner = "root"
mode = "0644"
src = "pebblescape.tmpl"
dest = "/etc/nginx/sites-enabled/pebblescape.conf"
check_cmd  = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"