[template]
keys = [
  "/pebblescape/apps",
]
owner = "root"
mode = "0644"
src = "pebblescape.tmpl"
dest = "/etc/nginx/conf.d/pebblescape.conf"
check_cmd  = "nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "nginx -s reload"