[template]
keys = [
  "/pebblescape/apps",
]
owner = "root"
mode = "0644"
src = "pebblescape.tmpl"
dest = "/etc/nginx/conf.d/pebblescape.conf"
check_cmd  = "/home/pebbles/confdcheck {{.src}}"
reload_cmd = "/etc/init.d/nginx reload"