---
nginx:
  user: www-data
  pid: /var/run/nginx.pid
  dir: /etc/nginx
  log_dir: /var/log/nginx
  worker_connections: 1024
  multi_accept: true
  event: epoll
  enable_access_log: true
  sendfile: "on"
  keepalive_timeout: 65
  server_names_hash_bucket_size: 64
  types_hash_max_size: 2048
  types_hash_bucket_size: 64
  proxy_read_timeout: 86400s # 1 day
  client_max_body_size: 100m
  gzip: "on"
  gzip_http_version: "1.0"
  gzip_comp_level: "2"
  gzip_proxied: any
  gzip_vary: "off"
  gzip_types:
  - "text/plain"
  - "text/css"
  - "application/x-javascript"
  - "text/xml"
  - "application/atom+xml"
  - "application/xml"
  - "application/xml+rss"
  - "text/javascript"
  - "application/javascript"
  - "application/json"