---
- name: Download confd
  get_url: url=https://github.com/pebblescape/confd/releases/download/v0.8.0pre/confd-0.8.0pre-linux-amd64.linux dest=/root/confd
  
- name: Copy confd
  command: cp /root/confd /usr/local/bin/confd creates=/usr/local/bin/confd

- name: Set confd mode
  file: path=/usr/local/bin/confd mode=0777
  
- name: Make sure confd dir exists
  file: path=/etc/confd/conf.d recurse=yes state=directory
  
- name: Make sure confd dir exists
  file: path=/etc/confd/templates recurse=yes state=directory

- name: Transfer confd conf
  template: src=confd.toml.j2 dest=/etc/confd/confd.toml
  notify: restart confd
  
- name: Transfer confd nginx conf
  copy: src=nginx.toml dest=/etc/confd/conf.d/pebblescape.toml
  
- name: Transfer confd template
  copy: src=pebblescape.tmpl dest=/etc/confd/templates/pebblescape.tmpl
  notify: restart confd
  
- name: Transfer confd upstart script
  template: src=confd.conf.j2 dest=/etc/init/confd.conf
  notify: restart confd
  
- name: Restart confd 
  service: name=confd state=restarted